// HDMI to Mac SE monitor
// Andy Maxwell
// andy@maxwell.nyc
// 2025 07 20 version
// removing the external HDMI hardware and using the Gowin HDMI RX IP core

module main(


    output mac_hsync,
    output mac_vsync,
    output mac_active, // output for diagnostic
    output mac_pixel_clk, // output for diagnostic
    output reg video_out, // Changed to reg for procedural assignment

    // Universal reset (momentary push switch on T3 (Switch labeled 1))
    input rst, // Connect to FPGA pin T3
    // HDMI RX IP physical interface (to be connected to top-level or constraints)
    // (I_rst_n is now internal, see below)
    input I_tmds_clk_p, // HDMI_TXC_P (K14)
    input I_tmds_clk_n, // HDMI_TXC_N (K15)
    input [2:0] I_tmds_data_p, // [2]=G16, [1]=J15, [0]=H14
    input [2:0] I_tmds_data_n, // [2]=H15, [1]=K16, [0]=H16


    // --- Switches and LEDs for test settings, not used currently ---
    input T5  // Switch for Number5
//    input T4,  // Switch for Number4
//    input E8,  // Switch for Number3


    // output reg LED5_L16, 
    // output reg LED4_L14, 
    // output RBG_CLOCK_LED3_N14,  // for incoming HDMI pixel clock divider
    // output HDMI_ACTIVE_LED2_N16 // for incoming HDMI active

/// <<<<<<< HEAD
    // couple of outputs for the o'scope
    output J14,
    output J16,
    output M14,
    output M15,
    output T12,
    output R11,
    output T11,
    output P11

=======
    // (oscope outputs removed to avoid pin conflicts)
>>>>>>> b6359de7b4f878b890109c2e4071990f61f462af
);

    // --- Clock Generation and Buffering for 15.xx MHz pixel clock ---
    // still not exactly right, but close enough
    // The clock is generated by the Gowin oscillator and then passed through a PLL
    // to get the right frequency for the Mac SE
    wire osc_clk_raw; // Raw oscillator output
    wire fifteen_clk; // Buffered clock for logic

    // get the clock, should be 125MHz (or 250MHz/2, see gowin_osc.v)
    Gowin_OSC u_osc_generator (
        .oscout(osc_clk_raw) // Connect oscillator output
    );

    // then do some fancy-dancy math with the PLL 
    // to get it to 15.6672MHz (but still not right)
    Gowin_rPLL mac_clock_pll(
        .clkout(fifteen_clk), // Buffered clock output
        .clkin(osc_clk_raw)   // Raw clock input
    );

    assign mac_pixel_clk = fifteen_clk;

    ///////////////////////////
    // FRAMEBUFFER BRAM SECTION
    ////////////////////////////
    // the BRAM is semi dual port, 
    // port A is write only to take data in from HDMI (TODO)
    // port B is read-only to read data from the framebuffer and output it to the screen
    // it is 175104 x 1, pass in the pixel counter to read.
    // Initialized with the Susan Kare original Mac icon.  [:^)]]

    // --- BRAM for Frame Buffer ---
    wire [17:0] ada, adb; // Address inputs
    wire din, dout;       // Data inputs/outputs
    wire clka, cea, reseta, clkb, ceb, resetb, oce; // Control signals - removed wea

    Gowin_SDPB framebuffer(
        .dout(dout),
        .clka(clka),
        .cea(cea),
        .reseta(rst),
        .clkb(clkb),
        .ceb(ceb),
        .resetb(rst), // use rst for both ports
        .oce(oce),
        .ada(ada),
        .din(din),
        .adb(adb)
    );

    //////////////////////////////////
    // --- Mac SE Timing Generator ---
    //////////////////////////////////
    wire [9:0] mac_x_coord;
    wire [8:0] mac_y_coord;
    wire [17:0] mac_pixel; // Pixel counter

    mac_se_timing_generator mac_timer(
        .clk(fifteen_clk),
        .hsync(mac_hsync),
        .vsync(mac_vsync),
        .active(mac_active),
        .pixel_x(mac_x_coord),
        .pixel_y(mac_y_coord),
        .pixel(mac_pixel)
    );

    // so now with every clock cycle the box should be spitting out perfect 
    // Mac SE VSYNC, and HSYNC signals, just like Woz used to make.
    // Internally, it's returning X & Y and total pixel count
    // to use to lookup black/white in the framebuffer
    // in the same time domain as the VSYNC and HSYNC


    // --- Mac CLock Time Domain Framebuffer Address and Clock Feeding ---
    // port B is read-only, port A is write-only
    assign clkb = fifteen_clk; // Use the pixel clock for framebuffer
    assign ceb = 1'b1;         // Enable framebuffer read
    assign adb = mac_pixel;    // Address is the pixel counter

    // Ensure BRAM output is valid
    assign oce = 1'b1;         // Output clock enable for BRAM

    // whenever the clock goes low, get the current pixel out of the framebuffer
    // and send it right out of the board i/o to make a beautiful picture
    always @(posedge fifteen_clk) begin
        video_out <= !(mac_active & dout); // Use AND condition for video_out
    end

    /////////////////////////////
    // HDMI RX IP INTEGRATION  //
    /////////////////////////////


    // TODO: Hook up these to the pins in the Dock specs
    // turn on HPD and DCC.  
    // hook clock up to some sort of clock.
    // resest to reset.

    // 600x600 EDID to tell the computer to do that resolution
	EDID_PROM_Top edid_prom(
		.I_clk(I_clk), //input I_clk
		.I_rst_n(I_rst_n), //input I_rst_n
		.I_scl(I_scl), //input I_scl
		.IO_sda(IO_sda) //inout IO_sda  
	);



<<<<<<< HEAD
    // Simplified Coordinate Generation Registers
    reg [9:0] input_x; // Input X coordinate (10 bits for H_ACTIVE)
    reg [8:0] input_y; // Input Y coordinate (9 bits for V_ACTIVE)
    reg input_coord_valid;             // Valid signal for input coordinates
    reg rgb_hsync_prev;
    reg rgb_vsync_prev;
    reg rgb_de_prev;
    reg mono_pixel; // Monochrome pixel output (1 bit)
    
    // NEW: Sync flag registers - only driven from pixel clock domain
    reg newV; // VSYNC event flag - set by VSYNC detection, cleared after processing
    reg newH; // HSYNC event flag - set by HSYNC detection, cleared after processing
    
    // Sync edge detection registers (for pixel clock domain)
    reg rgb_vsync_sync1, rgb_vsync_sync2; // VSYNC synchronizer chain
    reg rgb_hsync_sync1, rgb_hsync_sync2; // HSYNC synchronizer chain
=======
>>>>>>> b6359de7b4f878b890109c2e4071990f61f462af



    // Internal wires for DVI_RX_Top outputs
    wire O_pll_lock;
    wire [3:0] O_pll_phase;
    wire O_pll_phase_lock;
    wire O_rgb_clk;
    wire O_rgb_vs;
    wire O_rgb_hs;
    wire O_rgb_de;
    wire [7:0] O_rgb_r;
    wire [7:0] O_rgb_g;
    wire [7:0] O_rgb_b;

<<<<<<< HEAD
    // *** BRAM Interface Registers (KEEP THESE) ***
    reg [17:0] bram_addr_reg; // BRAM address register (18 bits for 512x342)
    reg bram_din_reg;
    reg bram_ena_reg; // Port Enable register for BRAM
    //reg bram_wea_reg; // Write Enable register for BRAM

    // Intermediate Wires - SIMPLIFIED
    // No edge detection needed - using direct clock edges

    // Combinatorial calculation for next BRAM address
    wire [17:0] next_bram_addr = (scaled_write_y * H_SCALED) + scaled_write_x;

    // --- Logic Implementation ---

    // --- PIXEL CLOCK: Handle all logic in single clock domain with sync detection ---
    always @(posedge rgb_odck) begin
        // --- Synchronize sync signals to pixel clock domain ---
        rgb_vsync_sync1 <= rgb_vsync;
        rgb_vsync_sync2 <= rgb_vsync_sync1;
        rgb_hsync_sync1 <= rgb_hsync;
        rgb_hsync_sync2 <= rgb_hsync_sync1;
        
        // --- Detect rising edges of synchronized signals ---
        if (rgb_vsync_sync1 && !rgb_vsync_sync2) begin
            // VSYNC rising edge detected
            newV <= 1'b1;
        end
        
        if (rgb_hsync_sync1 && !rgb_hsync_sync2) begin
            // HSYNC rising edge detected  
            newH <= 1'b1;
        end

        // --- Latch Previous States for debugging ---
        rgb_hsync_prev <= rgb_hsync;
        rgb_vsync_prev <= rgb_vsync;
        rgb_de_prev    <= rgb_de;

        // --- VSYNC flag: Reset frame ---
        if (newV) begin
            // VSYNC event detected - reset frame
            input_y <= 0;
            input_x <= 0;
            newV <= 1'b0;  // Clear the flag
        end
        // --- HSYNC flag: Reset line and increment Y ---
        else if (newH) begin
            // HSYNC event detected - reset X counter, increment Y
            input_x <= 0;
            if (input_y < V_ACTIVE - 1) begin
                input_y <= input_y + 1;
            end
            newH <= 1'b0;  // Clear the flag
        end
        
        // --- X Counter: Increment during active video (independent of sync flags) ---
        if (rgb_de && input_x < H_ACTIVE - 1) begin
            // During active video - increment X counter
            input_x <= input_x + 1;
        end

        // Coordinate Valid Signal - simply follows DE
        input_coord_valid <= rgb_de;

        // --- Color Converter ---
        if (input_coord_valid) begin
            // Set mono_pixel high if any of R, G, or B are high
            mono_pixel <= rgb_r_B14 | rgb_g_A14 | rgb_b_b13;
        end else begin
            mono_pixel <= 1'b0;
        end

        // --- Scaler Logic ---
        // T5 switch: 1 = scaled mode, 0 = crop mode (top-left corner)
        if (input_coord_valid) begin // Uses previous cycle's valid implicitly
            if (!T5) begin
                // SCALED MODE: Scale 800x480 to 512x342
                scaled_write_x <= (input_x * H_SCALED) / H_ACTIVE;
                // Alternative Y scaling to ensure full range coverage
                if (input_y >= V_ACTIVE - 1) begin
                    scaled_write_y <= V_SCALED - 1; // Ensure we hit the last line
                end else begin
                    scaled_write_y <= (input_y * V_SCALED) / V_ACTIVE;
                end
            end else begin
                // CROP MODE: Direct 1:1 mapping (top-left 512x342 pixels)
                if (input_x < H_SCALED && input_y < V_SCALED) begin
                    scaled_write_x <= input_x[8:0]; // Take lower 9 bits 
                    scaled_write_y <= input_y[8:0]; // Take lower 9 bits
                end else begin
                    // Outside crop area - don't write
                    scaled_write_enable <= 1'b0;
                end
            end
            
            // Common logic for both modes
            if (T5 || (input_x < H_SCALED && input_y < V_SCALED)) begin
                scaled_mono_pixel <= mono_pixel;
                scaled_write_enable <= 1'b1;
            end
        end else begin
            scaled_write_enable <= 1'b0;
        end

        // --- Framebuffer Write Logic (Register BRAM Inputs) ---
        // Uses values from the *previous* cycle (scaler outputs)
        if (scaled_write_enable) begin
            bram_addr_reg <= next_bram_addr;    // Register address
            bram_din_reg  <= scaled_mono_pixel; // Register data
            bram_ena_reg  <= 1'b1;             // Register Port Enable (asserted)
            // bram_wea_reg  <= 1'b1;             // Register Write Enable (asserted)
        end else begin
            bram_ena_reg  <= 1'b0;             // Register Port Enable (deasserted)
            // bram_wea_reg  <= 1'b0;             // Register Write Enable (deasserted)
        end
    end

    // --- BRAM Interface Assignments ---
    // Assign BRAM inputs directly from the dedicated registers
    // For Gowin BRAM: cea controls both clock enable and write enable

    assign clka = rgb_odck; // BRAM clock
    assign ada = bram_addr_reg; // Use registered address (assuming Port A)
    assign din = bram_din_reg;   // Use registered data (assuming Port A)
    assign cea = bram_ena_reg;    // Clock Enable A also controls writes
                                // No separate write enable - Gowin BRAM uses cea for both
        
    //////  END OF GEMINI 
=======
    // Instantiate the HDMI RX IP (internal clock version)
    DVI_RX_Top dvi_rx(
        .I_rst_n(~rst), // active-low reset
        .I_tmds_clk_p(I_tmds_clk_p),
        .I_tmds_clk_n(I_tmds_clk_n),
        .I_tmds_data_p(I_tmds_data_p),
        .I_tmds_data_n(I_tmds_data_n),
        .O_pll_lock(O_pll_lock),
        .O_pll_phase(O_pll_phase),
        .O_pll_phase_lock(O_pll_phase_lock),
        .O_rgb_clk(O_rgb_clk),
        .O_rgb_vs(O_rgb_vs),
        .O_rgb_hs(O_rgb_hs),
        .O_rgb_de(O_rgb_de),
        .O_rgb_r(O_rgb_r),
        .O_rgb_g(O_rgb_g),
        .O_rgb_b(O_rgb_b)
    );

    // Simple coordinate generator for framebuffer write (HDMI domain)
    reg [9:0] hdmi_x;
    reg [8:0] hdmi_y;
    reg O_rgb_de_prev;
    reg O_rgb_vs_prev;
    wire de_rising = (O_rgb_de_prev == 1'b0 && O_rgb_de == 1'b1);
    wire de_falling = (O_rgb_de_prev == 1'b1 && O_rgb_de == 1'b0);
    wire vs_falling = (O_rgb_vs_prev == 1'b1 && O_rgb_vs == 1'b0);

    always @(posedge O_rgb_clk) begin
        O_rgb_de_prev <= O_rgb_de;
        O_rgb_vs_prev <= O_rgb_vs;
        if (vs_falling) begin
            hdmi_y <= 0;
        end else if (de_falling) begin
            hdmi_y <= hdmi_y + 1;
        end
        if (de_rising) begin
            hdmi_x <= 0;
        end else if (O_rgb_de) begin
            hdmi_x <= hdmi_x + 1;
        end
    end

    // Monochrome conversion (simple OR of MSBs)
    wire mono_pixel = O_rgb_r[7] | O_rgb_g[7] | O_rgb_b[7];

    // Framebuffer write enable logic
    wire fb_write_en = O_rgb_de && (hdmi_x < 512) && (hdmi_y < 342);
    wire [17:0] fb_addr = (hdmi_y * 512) + hdmi_x;
>>>>>>> b6359de7b4f878b890109c2e4071990f61f462af

    assign clka = O_rgb_clk;
    assign ada = fb_addr;
    assign din = mono_pixel;
    assign cea = fb_write_en;
    assign wea = fb_write_en;

    // HDMI activity LED (stub: always on if clock present)
    //assign HDMI_ACTIVE_LED2_N16 = O_rgb_clk;

    // (oscope assignments removed)

<<<<<<< HEAD
    // ACHTUNG! DAS INKOMMEN HDMI-SIGNAL IST NUN GE-AKTIVEN!
    assign HDMI_ACTIVE_LED2_N16 = ~rgb_active; // shine LED2 if HDMI is active


    // DEUGGER STUFF TO SEE IF THE RGB INPUTS ARE WORKING
    // --- rgb_odck activity indicator ---
    reg [23:0] rgb_odck_counter = 0;
    reg rgb_odck_blink = 0;
    always @(posedge rgb_odck) begin
        rgb_odck_counter <= rgb_odck_counter + 1;
        if (rgb_odck_counter == 24'd0) // overflow, about once per ~16M clocks
            rgb_odck_blink <= ~rgb_odck_blink;
    end

    assign RBG_CLOCK_LED3_N14 = rgb_odck_blink; // Blink LED3 on RGB clock activity


    // debugging - simplified signals
    assign J16 = rgb_vsync;           // Current VSYNC state
    assign J14 = rgb_hsync;           // Current HSYNC state  
    assign M14 = T5;                  // T5 switch state (1=scale, 0=crop) TODO: Isn't working.
    assign M15 = scaled_write_y[8];   // MSB of scaled Y (should reach 341 in scale mode)  
    assign T12 = rgb_de;              // Data Enable
    assign R11 = input_x[0];          // LSB of X counter
    assign T11 = input_y[0];          // LSB of Y counter
    assign P11 = bram_ena_reg;        // BRAM Write Enable for debugging
=======
    // LED3 stub (no blink logic for now)
    //assign RBG_CLOCK_LED3_N14 = 1'b1;


>>>>>>> b6359de7b4f878b890109c2e4071990f61f462af
endmodule
