module main(
    // input  Clock,

    output mac_hsync,
    output mac_vsync,
    output mac_active, // output for diagnostic
    output mac_pixel_clk, // output for diagnostic
    output reg video_out, // Changed to reg for procedural assignment

    // TTL RGB in
    input rgb_r0_L9, 
    input rgb_r1_N8, 
    // input rgb_r2_N9, // conflict, assigned to SSPI. Going to use 0 instead
    input rgb_r3_N7, 
    input rgb_r4_N6,


    input rgb_g0_D11,
    input rgb_g1_A11,
    input rgb_g2_B11,
    input rgb_g3_P7,
    input rgb_g4_R7,
    input rgb_g5_D10, // I don't know why Green has 6 bits and the others just get 5
    
    input rgb_b0_B12,
    input rgb_b1_C12,
    input rgb_b2_B13,
    input rgb_b3_A14,
    input rgb_b4_B14,

    input rgb_odck, // R9 PIXCLK
    input rgb_hsync, // A15
    input rgb_vsync,  // D15
    input rgb_de,  // E15 DISPEN on the Adafruit board schematic

    // input rgb_bl, // Backlight control, not used
    // input tp_* // for the Touch Screen, Mac SE doesn't have one.


    // --- Switches and LEDs for test settings, not used currently ---
    input T5,  // Switch for Number5
//    input T4,  // Switch for Number4
//    input E8,  // Switch for Number3


    output reg LED5_L16, 
    output reg LED4_L14, 
    output reg LED3_N14,  
    output reg LED2_N16,

    // couple of outputs for the o'scope
    output J14,
    output J16
);

    // --- Clock Generation and Buffering for 15.xx MHz pixel clock ---
    // still not exactly right, but close enough
    // The clock is generated by the Gowin oscillator and then passed through a PLL
    // to get the right frequency for the Mac SE
    wire osc_clk_raw; // Raw oscillator output
    wire fifteen_clk; // Buffered clock for logic

    // get the clock, should be 125MHz (or 250MHz/2, see gowin_osc.v)
    Gowin_OSC u_osc_generator (
        .oscout(osc_clk_raw) // Connect oscillator output
    );

    // then do some fancy-dancy math with the PLL 
    // to get it to 15.6672MHz (but still not right)
    Gowin_rPLL mac_clock_pll(
        .clkout(fifteen_clk), // Buffered clock output
        .clkin(osc_clk_raw)   // Raw clock input
    );

    assign mac_pixel_clk = fifteen_clk;

    ///////////////////////////
    // FRAMEBUFFER BRAM SECTION
    ////////////////////////////
    // the BRAM is semi dual port, 
    // port A is write only to take data in from HDMI (TODO)
    // port B is read-only to read data from the framebuffer and output it to the screen
    // it is 175104 x 1, pass in the pixel counter to read.
    // Initialized with the Susan Kare original Mac icon.  [:^)]]

    // --- BRAM for Frame Buffer ---
    wire [17:0] ada, adb; // Address inputs
    wire din, dout;       // Data inputs/outputs
    wire clka, cea, reseta, clkb, ceb, resetb, oce; // Control signals

    Gowin_SDPB framebuffer(
        .dout(dout),
        .clka(clka),
        .cea(cea),
        .reseta(1'b0),
        .clkb(clkb),
        .ceb(ceb),
        .resetb(1'b0), // reset should always be low to enable it
        .oce(oce),
        .ada(ada),
        .din(din),
        .adb(adb)
    );

    //////////////////////////////////
    // --- Mac SE Timing Generator ---
    //////////////////////////////////
    wire [9:0] mac_x_coord;
    wire [8:0] mac_y_coord;
    wire [17:0] mac_pixel; // Pixel counter

    mac_se_timing_generator mac_timer(
        .clk(fifteen_clk),
        .hsync(mac_hsync),
        .vsync(mac_vsync),
        .active(mac_active),
        .pixel_x(mac_x_coord),
        .pixel_y(mac_y_coord),
        .pixel(mac_pixel)
    );

    // so now with every clock cycle the box should be spitting out perfect 
    // Mac SE VSYNC, and HSYNC signals, just like Woz used to make.
    // Internally, it's returning X & Y and total pixel count
    // to use to lookup black/white in the framebuffer
    // in the same time domain as the VSYNC and HSYNC


    // --- Mac CLock Time Domain Framebuffer Address and Clock Feeding ---
    // port B is read-only, port A is write-only
    assign clkb = fifteen_clk; // Use the pixel clock for framebuffer
    assign ceb = 1'b1;         // Enable framebuffer read
    assign adb = mac_pixel;    // Address is the pixel counter

    // Ensure BRAM output is valid
    assign oce = 1'b1;         // Output clock enable for BRAM

    // whenever the clock goes low, get the current pixel out of the framebuffer
    // and send it right out of the board i/o to make a beautiful picture
    always @(posedge fifteen_clk) begin
        video_out <= !(mac_active & dout); // Use AND condition for video_out
    end

    /////////////////////////////
    /////// HDMI DECODER SECTION //////////
    /////////////////////////////
    ////  start of GEMINI

        // --- Corrected Input Coordinate Generator ---
    // Assumes standard video timing: DE high for active pixels,
    // HSync/VSync pulses occur during blanking (DE low).
    // Assumes HSync and VSync are active-low pulses (adjust if needed).
    // --- Simplified Coordinate Generator + Registered BRAM Interface ---

    // Define active display dimensions
    localparam H_ACTIVE = 800;
    localparam V_ACTIVE = 480;

    // Define scaled output dimensions
    localparam H_SCALED = 512;
    localparam V_SCALED = 342;
    localparam BRAM_ADDR_WIDTH = $clog2(H_SCALED * V_SCALED); // 18 bits for 512x342

    // --- Input Signal Declarations (Example) ---
    // wire rgb_odck;
    // wire rgb_de, rgb_hsync, rgb_vsync;
    // wire rgb_r3_N7,...; // Example color bits

    // --- Internal Registers and Wires ---

    // Simplified Coordinate Generation Registers
    reg [9:0] input_x; // Input X coordinate (10 bits for H_ACTIVE)
    reg [8:0] input_y; // Input Y coordinate (9 bits for V_ACTIVE)
    reg input_coord_valid;             // Valid signal for input coordinates
    reg rgb_hsync_prev;
    reg rgb_vsync_prev;
    reg rgb_de_prev;
    reg mono_pixel; // Monochrome pixel output (1 bit)

    // Color Conversion Wires (faster than registers in an ALWAYS)
    wire [7:0] red, green, blue;
    assign red[0]   = rgb_r0_L9; // 1 bit
    assign red[1]   = rgb_r1_N8; // 1 bit
    assign red[2]   = 1'b0; // 0 bit (unused)
    assign red[3]   = rgb_r3_N7; // 1 bit
    assign red[4]   = rgb_r4_N6; // 1 bit
    assign green[0] = rgb_g0_D11; // 1 bit
    assign green[1] = rgb_g1_A11; // 1 bit
    assign green[2] = rgb_g2_B11; // 1 bit
    assign green[3] = rgb_g3_P7; // 1 bit
    assign green[4] = rgb_g4_R7; // 1 bit
    assign green[5] = rgb_g5_D10; // 1 bit
    assign blue[0]  = rgb_b0_B12; // 1 bit
    assign blue[1]  = rgb_b1_C12; // 1 bit
    assign blue[2]  = rgb_b2_B13; // 1 bit
    assign blue[3]  = rgb_b3_A14; // 1 bit
    assign blue[4]  = rgb_b4_B14; // 1 bit

    // Sum the RGB wires
    wire [8:0] rgb_sum = red + green + blue;

    // Scaler Registers
    reg [8:0] scaled_write_x; // Scaled X coordinate (9 bits for H_SCALED)
    reg [8:0] scaled_write_y; // Scaled Y coordinate (9 bits for V_SCALED)
    reg scaled_mono_pixel;
    reg scaled_write_enable;

    // *** BRAM Interface Registers (KEEP THESE) ***
    reg [17:0] bram_addr_reg; // BRAM address register (18 bits for 512x342)
    reg bram_din_reg;
    reg bram_ena_reg; // Port Enable register for BRAM
    reg bram_wea_reg; // Write Enable register for BRAM

    // Intermediate Wires
    // Detect falling edges (assuming active-low syncs)
    wire hsync_falling_edge = (rgb_hsync_prev == 1'b1 && rgb_hsync == 1'b0);
    wire vsync_falling_edge = (rgb_vsync_prev == 1'b1 && rgb_vsync == 1'b0);
    wire de_rising_edge   = (rgb_de_prev == 1'b0 && rgb_de == 1'b1);

    // Combinatorial calculation for next BRAM address
    wire [17:0] next_bram_addr = (scaled_write_y * H_SCALED) + scaled_write_x;

    // --- Logic Implementation ---

    always @(posedge rgb_odck) begin
        // --- Latch Previous States ---
        rgb_hsync_prev <= rgb_hsync;
        rgb_vsync_prev <= rgb_vsync;
        rgb_de_prev    <= rgb_de;

        // --- Simplified Input Coordinate Generator ---
        // Horizontal Counter (input_x)
        if (rgb_de) begin // Only count during active horizontal display
            if (de_rising_edge) begin // Reset X at start of active line
                input_x <= 0;
            end else if (input_x < H_ACTIVE - 1) begin
                input_x <= input_x + 1; // Increment X during active display
            end
        end

        // Vertical Counter (input_y)
        // Reset Y on VSync edge (detect during blanking)
        if (vsync_falling_edge &&!rgb_de) begin // Check DE is low
            input_y <= 0;
        // Increment Y on HSync edge (detect during blanking)
        end else if (hsync_falling_edge &&!rgb_de) begin // Check DE is low
            if (input_y < V_ACTIVE - 1) begin
                input_y <= input_y + 1;
            end
        end

        // Coordinate Valid Signal - simply follows DE in this version
        input_coord_valid <= rgb_de;

        // --- Color Converter ---
        if (input_coord_valid) begin
            // Compare the OR of all to a threshold
            mono_pixel <= (rgb_sum > 8'd60) ? 1'b1 : 1'b0;
        end else begin
            mono_pixel <= 1'b0;
        end

        // --- Scaler Logic ---
        // (Consider pipelining multiply/divide if timing is an issue)
        if (input_coord_valid) begin // Uses previous cycle's valid implicitly
            scaled_write_x <= (input_x * H_SCALED) / H_ACTIVE;
            scaled_write_y <= (input_y * V_SCALED) / V_ACTIVE;
            scaled_mono_pixel <= mono_pixel;
            scaled_write_enable <= 1'b1;
        end else begin
            scaled_write_enable <= 1'b0;
        end

        // --- Framebuffer Write Logic (Register BRAM Inputs) ---
        // Uses values from the *previous* cycle (scaler outputs)
        if (scaled_write_enable) begin
            bram_addr_reg <= next_bram_addr;    // Register address
            bram_din_reg  <= scaled_mono_pixel; // Register data
            bram_ena_reg  <= 1'b1;             // Register Port Enable (asserted)
            bram_wea_reg  <= 1'b1;             // Register Write Enable (asserted)
        end else begin
            bram_ena_reg  <= 1'b0;             // Register Port Enable (deasserted)
            bram_wea_reg  <= 1'b0;             // Register Write Enable (deasserted)
        end
    end

    // --- BRAM Interface Assignments ---
    // Assign BRAM inputs directly from the dedicated registers
    // Ensure these port names match your BRAM primitive/inferred block

    assign clka = rgb_odck; // BRAM clock
    assign ada = bram_addr_reg; // Use registered address (assuming Port A)
    assign din = bram_din_reg;   // Use registered data (assuming Port A)
    assign cea = bram_ena_reg;    // Connect to Port A Enable (ENA)
    //assign wea = bram_wea_reg;    // Connect to Port A Write Enable (WEA)
                                // Adjust based on your BRAM's data width and primitive.
        
    //////  END OF GEMINI 


    // debugging
    //assign P9 = input_y[3]; // Output for oscilloscope

    
    // debugging
    assign J16 = rgb_de; // Output for oscilloscope Line 1
    assign J14 = mono_pixel; // Output for oscilloscope Line 2


endmodule
